### ISSUE TITLE
Describe structure of data sets

### ISSUE THREAD

**Issue by ggrothendieck** [svmiller/stevedata#1]
Suggest adding this to the vignette and website documentation so that one can quickly narrow down which datasets may be of interest.  Right now one has to go to the help pages one by one to discover this.

af_crime is a 51 x 8 data frame. First column is character. Others are numeric.

aluminum_premiums is a 2812 x 3 data frame with date, factor and numeric columns.

etc.

**Comment by svmiller** [comment]
Neat idea. I wish there was a way of automating this in {pkgdown} or something similar, but it could be done through the {tools} package too.

**Comment by svmiller** [comment]
Finally coming around to this. I will assuredly tweak this to make it better, but even doing this has pointed me to some important information about the data in the package.

http://svmiller.com/stevedata/articles/stevedata-description.html
